version: 2.1

jobs:
  check_tf_formatting:
    docker:
      - image: cimg/deploy:2024.11
   
    steps:
      - checkout
      - run:
          name: echo Terraform version
          command: |
            terraform version
      - run:
          name: Terraform fmt to provoke issues
          command: |
            terraform fmt -check -recursive; test $? -eq 0 

  lint:
    docker:
      - image: cimg/deploy:2024.11
   
    steps:
      - checkout
      # turn on docker to allow docker run
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: set up tflint from dockerfile
          command: |
            docker build -f Dockerfile_tflint -t $(pwd | xargs basename):latest .
      - run:
          name: tflint version
          command: |
            docker run \
            --rm -t $(pwd | xargs basename):latest \
            --version
      - run:
          name: set up tflint from dockerfile
          command: |
            docker run \
            --rm -t $(pwd | xargs basename):latest \
            --recursive --format=compact 
workflows:
  format_lint_checks:
    jobs:
    - check_tf_formatting
    - lint
