version: 2.1


jobs:
  check_tf_formatting:
    docker:
      - image: cimg/deploy:2023.06
   
    steps:
      - checkout
      - run:
          name: check version
          command: |
            terraform version

workflows:
  format_lint_checks:
    jobs:
    - check_tf_formatting
