version: 2.1


jobs:
  check_tf_formatting:
    docker:
      - image: cimg/deploy:2023.06
   
    steps:
      - checkout
      - run:
          name: echo Terraform version
          command: |
            terraform version

      - run:
          name: Terraform fmt to provoke issues
          command: |
            terraform fmt -check ; test $? -eq 0 

workflows:
  format_lint_checks:
    jobs:
    - check_tf_formatting
