version: 2.1

jobs:
  check_tf_formatting:
    docker:
      - image: cimg/deploy:2024.11
   
    steps:
      - checkout
      - run:
          name: echo Terraform version
          command: |
            terraform version

      - run:
          name: Terraform fmt to provoke issues
          command: |
            terraform fmt -check -recursive; test $? -eq 0 

  lint:
    docker:
      - image: cimg/deploy:2024.11
   
    steps:
      - checkout
      # turn on docker to allow docker run
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: run tflint from docker image
          command: |
            docker run --rm -t ghcr.io/terraform-linters/tflint --version


workflows:
  format_lint_checks:
    jobs:
    - check_tf_formatting
    - lint
